dist: trusty
language: node_js
node_js:
  - 10
services:
  - docker
cache:
  npm: true
  directories:
    - ~/.cache
before_script:
  - npm install -g @angular/cli
install:
  - npm ci
stages:
  - name: linter
    if: branch = master
  - name: unit-tests
    if: branch = master
  - name: e2e
    if: branch = master
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: linter
      script: npm run lint
    - stage: unit-tests
      script: bash ./ci/unit-tests
    - stage: e2e
      script: bash ./ci/e2e
    - stage: deploy
      script: 
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./ci/deploy && bash ./ci/release; fi'
