version: 2.1
aliases:
  restore_cache: &restore_cache
    restore_cache:
      name: Restore Npm Package Cache
      keys:
        - v1-dependencies-{{ checksum "package-lock.json" }}

  save_cache: &save_cache
    save_cache:
      name: Save NPM modules cache
      paths:
        - ./node_modules
      key: v1-dependencies-{{ checksum "package-lock.json" }}
  
  store_dist: &store_dist
    save_cache:
      name: Save dist folder
      paths:
        - dist
      key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
  
  restore_dist: &restore_dist
    restore_cache:
      name: Restore built dist folder
      keys:
        - v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

  install_node_modules: &install_node_modules
    run:
      name: Install local dependencies
      command: npm ci
      when: always

  show_bash_version: &show_bash_version
    run:
      name: Show current bash version
      command: echo ${BASH_VERSION}
jobs:
  linter:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - <<: *show_bash_version
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *save_cache
      - run:
          name: Linting
          command: ./ci/linter
  unit-tests:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - <<: *show_bash_version
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *save_cache
      - run:
          name: Unit tests
          command: ./ci/unit-tests
  e2e:
    docker:
      - image: cypress/base:10
    working_directory: ~/repo
    steps:
      - checkout
      - <<: *show_bash_version
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *save_cache
      - run:
          name: e2e tests
          command: ./ci/e2e
workflows:
  version: 2
  angular-chile-pipeline:
    jobs:
      - linter
      - unit-tests
      - e2e